# Generated by Django 2.2.6 on 2022-11-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_renda', models.CharField(max_length=200)),
                ('valor_renda', models.IntegerField()),
            ],
        ),
    ]
