# Generated by Django 2.2.6 on 2022-11-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('codigo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('idade', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=20)),
                ('altura', models.CharField(max_length=20)),
                ('masculino', models.BooleanField(default=True)),
                ('subescapular', models.CharField(max_length=20)),
                ('tricipital', models.CharField(max_length=20)),
                ('peitoral', models.CharField(max_length=20)),
                ('axilar_medio', models.CharField(max_length=20)),
                ('suprailiaca', models.CharField(max_length=20)),
                ('coxa', models.CharField(max_length=20)),
                ('abdomen_dobra', models.CharField(max_length=20)),
                ('torax', models.CharField(max_length=20)),
                ('braco_relaxado', models.CharField(max_length=20)),
                ('braco_contraido', models.CharField(max_length=20)),
                ('antebraco', models.CharField(max_length=20)),
                ('abdomen_perimetria', models.CharField(max_length=20)),
                ('cintura', models.CharField(max_length=20)),
                ('quadril', models.CharField(max_length=20)),
                ('coxas', models.CharField(max_length=20)),
                ('panturrilha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('codigo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nome_renda', models.CharField(max_length=20)),
                ('valor_renda', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=200)),
                ('treinador', models.BooleanField()),
            ],
        ),
    ]
