# Generated by Django 2.2.6 on 2022-11-23 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rendas',
            new_name='Renda',
        ),
    ]
