# Generated by Django 2.2.6 on 2022-11-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinador', '0002_auto_20221123_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('idade', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=20)),
                ('altura', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=20)),
                ('subescapular', models.CharField(max_length=20)),
                ('tricipital', models.CharField(max_length=20)),
                ('peitoral', models.CharField(max_length=20)),
                ('axilar_medio', models.CharField(max_length=20)),
                ('suprailiaca', models.CharField(max_length=20)),
                ('coxa', models.CharField(max_length=20)),
                ('abdomen_dobra', models.CharField(max_length=20)),
                ('torax', models.CharField(max_length=20)),
                ('braco_relaxado', models.CharField(max_length=20)),
                ('braco_contraido', models.CharField(max_length=20)),
                ('antebraco', models.CharField(max_length=20)),
                ('abdomen_perimetria', models.CharField(max_length=20)),
                ('cintura', models.CharField(max_length=20)),
                ('quadril', models.CharField(max_length=20)),
                ('coxas', models.CharField(max_length=20)),
                ('panturrilha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=200)),
                ('tipo_usuario', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='renda',
            name='nome_renda',
            field=models.CharField(max_length=20),
        ),
    ]
